#app.yaml
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: predict
  CLOUD_SQL_PASSWORD: *******
  CLOUD_SQL_DATABASE_NAME: predict
  CLOUD_SQL_CONNECTION_NAME: jovial-light-312714:asia-southeast2:predict
